apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deployment
  labels:
    app: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: dockingsameer/notifierappimage:latest