# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/fileTransfer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/fileTransfer.proto\x12\x04\x63omm\"!\n\x0eStringResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0c\x46ileResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"X\n\x11UploadFileRequest\x12\"\n\x08metadata\x18\x01 \x01(\x0b\x32\x0e.comm.MetaDataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request2\x87\x01\n\x0c\x66ileTransfer\x12?\n\nUploadFile\x12\x17.comm.UploadFileRequest\x1a\x14.comm.StringResponse\"\x00(\x01\x12\x36\n\x0c\x44ownloadFile\x12\x0e.comm.MetaData\x1a\x12.comm.FileResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.fileTransfer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGRESPONSE._serialized_start=35
  _STRINGRESPONSE._serialized_end=68
  _FILERESPONSE._serialized_start=70
  _FILERESPONSE._serialized_end=104
  _METADATA._serialized_start=106
  _METADATA._serialized_end=153
  _UPLOADFILEREQUEST._serialized_start=155
  _UPLOADFILEREQUEST._serialized_end=243
  _FILETRANSFER._serialized_start=246
  _FILETRANSFER._serialized_end=381
# @@protoc_insertion_point(module_scope)
